### ISSUE TITLE
Getting output value from more than one step renders the workflow inexportable

### ISSUE THREAD

**Issue by irtzonevrakis** [kantale/OpenBio.eu#242]
Steps to reproduce:

1. Create a new workflow named 'test' with an output 'outp1'
2. Create a step 'step1' with the following bash code:
`output__outp1__test__1="test"`
3. Create a step 'step2' with the following bash code:
`echo ${output__outp1__test__1}`
4. Add the following bash code to the main step:
```{bash}
step__step1__test__1
step__step2__test__1
```

5. Save the workflow, then export it to Argo.

Expected result: Workflow is exported normally.

Actual result: The system errors out with 'OBC: Output variable: output__outp1__test__1 is set by more than one steps: step__step1__test__1 step__step2__test__1 ', even though 'outp1' is only set in step1.

I have attached the JSON of the minimal reproducible example discussed above.
[workflow_bug.zip](https://github.com/kantale/OpenBio.eu/files/7739774/workflow_bug.zip)

**Comment by kantale** [comment]
Confirmed.

**Comment by kantale** [comment]
The problem:
In line 565 (executor.py) it clearly mentions:
```
        The 'inputs' and 'outputs' fields for every step does NOT contain which variables are set and read respectively.
        It contains which variables are **referred**
```

Yet in lines removed from f463030 the `outputs` fields were treated as only setting the variables
