### ISSUE TITLE
Ranged PARALLEL does not expand properly when multiple arguments are passed

### ISSUE THREAD

**Issue by irtzonevrakis** [kantale/OpenBio.eu#245]
```
N="N
1:20"
PARALLEL step__parallel_step__ptest__1 "${N}"
```
works;
However,
```
N="N,N2
1:20, 1:30"
PARALLEL step__parallel_step__ptest__1 "${N}"
```
or
```
N="N,N2
1:20, 10"
PARALLEL step__parallel_step__ptest__1 "${N}"
```
or
```
N="N,N2
1:20, test"
PARALLEL step__parallel_step__ptest__1 "${N}"
```
do not correctly expand.

Contents of `parallel_step`:
```
echo ${N} ${N2}
```

**Comment by kantale** [comment]
Confirmed.
It shouldn't be hard to fix this.
```
1:20, 1:30"
```
Here, it must be the space after the coma.

The rest two:
```
1:20, 10"
```

```
1:20, test"
```

Are features that are not implemented. 

Will fix them asap.

**Comment by irtzonevrakis** [comment]
> Here, it must be the space after the coma.

Confirmed! Perhaps we should strip() the comma-separated data from the parallel variable, since even simple string arguments end up with extraneous left/right spaces if the user puts a space after their comma for style purposes (or add a note to the documentation about PARALLEL requiring strict CSV syntax to avoid unexpected behavior/extraneous spaces).
