### ISSUE TITLE
Attempting to view a tool while editing another tool makes old tool text persist after closing

### ISSUE THREAD

**Issue by irtzonevrakis** [kantale/OpenBio.eu#247]
How to reproduce:

1. Open and edit a tool
2. Try opening another tool while editing
3. An error message appears ('There are unsaved info on Tools/Data. Save or press Cancel'), as expected
4. Close out of the editing view by clicking 'Cancel'
5. Open the tool you tried to open
6. The installation / verification commands of the tool that was being edited in step (2) will appear instead of the commands of the tool being opened. Clicking on the relevant textboxes will load the proper text.

**Comment by irtzonevrakis** [comment]
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0

**Comment by kantale** [comment]
Confirmed.

**Comment by kantale** [comment]
Fixed!
Interestingly the same thing could happen in the step editor in workflows.
