### ISSUE TITLE
Argo: System-level tools aren’t available in their dependent workflows

### ISSUE THREAD

**Issue by irtzonevrakis** [kantale/OpenBio.eu#256]
Steps to reproduce:

1. Drop a tool that installs wget via apt-get to a new workflow’s DAG
2. Wget a file from the main step
3. Save the workflow, and run it on argo

Expected result:

The file is wgetted successfully

Actual result:

```
openbio-ow9id7vj-231601847: /root/step_bash.sh: line 18: wget: command not found
```

Minimal Reproducible Example:
See attached DAG JSON:
[workflow_dag.zip](https://github.com/kantale/OpenBio.eu/files/8253013/workflow_dag.zip)

**Comment by irtzonevrakis** [comment]
Thank you for the explanation! I assumed that, since in this case there was only one dependent tool, it would simply run `main_step` using the image that had `wget` installed in it. I'd like to propose one change in the documentation, though: Since the location where wget is installed is not a given, I think setting `tool_wget` to `$(which wget)` rather than any absolute path would be better in terms of flexibility/portability.

**Comment by kantale** [comment]
> I think setting tool_wget to $(which wget) rather than any absolute path would be better in terms of flexibility/portability.

Nice idea! I haven't tried to use any non-literal value to a tool variable thus far. So I will test it before updating the docs.

**Comment by irtzonevrakis** [comment]
FYI, I am currently setting most of my tool variables to non-literal values (containing ${OBC_TOOL_PATH}, ${OBC_DATA_PATH}, and now $(which ...)) and haven't had any issues so far.
